name: test

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "test/improve-test-coverage"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Checkout"
        uses: actions/checkout@v6

      - name: "Setup up java"
        uses: actions/setup-java@v5
        with:
          java-version: "21"
          distribution: "liberica"

      - name: "Setup gradle"
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-disabled: true

      - name: "Verify Java formatting"
        id: spotless
        continue-on-error: true
        run: ./gradlew spotlessJavaCheck

      - name: "Run tests"
        run: ./gradlew :sdk:test --no-daemon

      - name: "Fail if Java formatting check failed"
        if: steps.spotless.outcome == 'failure'
        run: exit 1

